#!/bin/sh
# Writes docs/api.txt: every public symbol of the zokor package (src/),
# one line of signature and one line of what it is for, taken from the
# comment directly above it. Generated so it cannot drift: CI runs
# `docs/gen_api.sh --check`, which fails when the committed file differs
# from what the sources say. Plain sh + awk, no slangc needed.
#
#   docs/gen_api.sh           rewrite docs/api.txt
#   docs/gen_api.sh --check   exit 1 if docs/api.txt is stale
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/api.txt"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT INT TERM

gen() {
    cat <<'HEAD'
# zokor API (generated by docs/gen_api.sh from src/; do not edit)
#
# `import "zokor";` then `zokor.<name>`. Methods are `value.name(..)`;
# `self` is omitted. Times are int nanoseconds, statuses i32.
# Recipes: docs/llms-small.txt.
HEAD
    for f in "$ROOT"/src/*.sl; do
        case "$f" in *_test.sl) continue ;; esac
        awk -v file="$(basename "$f")" '
        function trim(s) { sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s); return s }
        function first_sentence(s,   i, cut) {
            s = trim(s)
            i = index(s, ". ")
            if (i > 0) s = substr(s, 1, i)
            if (length(s) > 130) {
                cut = substr(s, 1, 127)
                sub(/ [^ ]*$/, "", cut)
                s = cut "..."
            }
            return s
        }
        function flush_doc() { doc = ""; }
        function emit(sig, d) {
            if (!header_done) {
                printf "\n## %s", file
                if (filedoc != "") printf " -- %s", first_sentence(filedoc)
                printf "\n"
                header_done = 1
            }
            print sig
            if (d != "") print "    " first_sentence(d)
        }
        BEGIN { doc = ""; filedoc = ""; infile_head = 1; impl = ""; mode = "" }
        # the file comment: the first comment block, before any code
        infile_head && /^\/\// { line = $0; sub(/^\/\/ ?/, "", line); if (line == "") { infile_head = 0; next } filedoc = filedoc " " line; next }
        infile_head && !/^\/\// { infile_head = 0 }
        mode == "sig" {
            line = trim($0)
            sig = sig " " line
            if (line ~ /\{$/) { mode = ""; finish_sig() }
            next
        }
        mode == "struct" {
            line = $0
            sub(/\/\/.*/, "", line)
            line = trim(line)
            if (line ~ /^\}/) {
                sub(/, *$/, "", body)
                emit(kind " " name " { " body " }", sdoc)
                mode = ""; body = ""; flush_doc(); next
            }
            if (line == "") next
            sub(/,$/, "", line)
            body = (body == "" ? line : body ", " line)
            next
        }
        /^[ \t]*\/\// {
            line = $0; sub(/^[ \t]*\/\/ ?/, "", line)
            doc = (doc == "" ? line : doc " " line)
            next
        }
        /^impl / { impl = $2; sub(/\[.*/, "", impl); flush_doc(); next }
        /^\}/ { impl = ""; flush_doc(); next }
        /^(pub )?(gc )?(struct|enum) / && /^pub / {
            kind = $0; sub(/^pub /, "", kind); sub(/ [A-Za-z_][A-Za-z0-9_]*(\[[^]]*\])? *\{.*/, "", kind)
            name = $0; sub(/^pub (gc )?(struct|enum) /, "", name); sub(/ *\{.*/, "", name)
            sdoc = doc
            rest = $0; sub(/^[^{]*\{/, "", rest)
            if (rest ~ /\}/) { sub(/\}.*/, "", rest); emit(kind " " name " { " trim(rest) " }", sdoc); flush_doc(); next }
            mode = "struct"; body = ""; next
        }
        /^[ \t]*pub fn / {
            sig = trim($0); fdoc = doc
            if (sig ~ /\{$/) finish_sig(); else mode = "sig"
            next
        }
        { flush_doc() }
        function finish_sig(   s) {
            s = sig
            sub(/^pub fn /, "", s)
            sub(/ *\{$/, "", s)
            gsub(/\( /, "(", s); gsub(/ +/, " ", s)
            if (impl != "") {
                sub(/\(self: [^,)]*(, )?/, "(", s)
                s = impl "." s
            }
            emit(s, fdoc)
            flush_doc()
        }
        ' "$f"
    done
    # The one internal type a caller sets fields on, through UploadRules.
    printf '\n## internal/multipart (reached as UploadRules.limits)\n'
    awk '
        /^pub gc struct Limits/ { on = 1; body = ""; next }
        on && /^\}/ { sub(/, *$/, "", body); print "gc struct Limits { " body " }"; on = 0; next }
        on { line = $0; sub(/\/\/.*/, "", line); gsub(/^[ \t]+|[ \t,]+$/, "", line); if (line != "") body = (body == "" ? line : body ", " line) }
    ' "$ROOT/src/internal/multipart/multipart.sl"
}

gen > "$TMP"
if [ "${1:-}" = "--check" ]; then
    if ! cmp -s "$TMP" "$OUT"; then
        echo "api: docs/api.txt is stale; run docs/gen_api.sh and commit it" >&2
        diff "$OUT" "$TMP" | head -20 >&2 || true
        exit 1
    fi
    echo "PASS docs/api.txt is up to date"
    exit 0
fi
cp "$TMP" "$OUT"
echo "wrote docs/api.txt ($(wc -c < "$OUT") bytes)"
